[package]
org = "evento-globolo"
name = "evgl-mash-web"
version = "0.1.0"
description = "Rust web server for Evento Globolo"
license = "MIT"
language = "rust"

[package.repository]
vcs = "git"
url = "https://github.com/evento-globolo/evgl-mash-web"

[publish]
include_readme = true
tag_format = "v{version}"
exclude = [".env", ".env.*", "node_modules/**", ".vendor/.zed/**", "target/**", "dist/**", "*.log"]

[dependencies]
"evento-globolo/evgl-lib-core" = "^0.1.0"
"evento-globolo/evgl-orm-core" = "^0.1.0"
"evento-globolo/evgl-interfaces" = "^0.1.0"
"evento-globolo/evgl-libs" = "^0.1.0"
"evento-globolo/evgl-sync" = "^0.1.0"
"shared-auth/shared-auth-clients" = "^0.1.0"
"oresoftware/ores-sw" = "^0.1.0"

[install]
dir = ".vendor/.zed"
adapter = "rust"